ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS default_currency CHAR(3) NOT NULL DEFAULT 'AUD',
  ADD COLUMN IF NOT EXISTS default_timezone VARCHAR(64) NOT NULL DEFAULT 'Australia/Sydney';

ALTER TABLE stores
  ADD COLUMN IF NOT EXISTS address TEXT NULL,
  ADD COLUMN IF NOT EXISTS google_maps_url VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS logo_path VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS currency_code CHAR(3) NULL,
  ADD COLUMN IF NOT EXISTS timezone VARCHAR(64) NULL;
