<?php
declare(strict_types=1);
$_SERVER['REQUEST_METHOD']=$_SERVER['REQUEST_METHOD']??'CLI';
require_once dirname(__DIR__).'/api/config.php';
const FINFX='AUTOTEST Finance E2E';
function fxfail(string $m): never { fwrite(STDERR,"FINANCE_E2E_FIXTURE_FAIL {$m}\n"); exit(1); }
function fxclient(PDO $p): array { $r=$p->query("SELECT id,client_code,status FROM clients WHERE UPPER(client_code)='DUMMY' LIMIT 2")->fetchAll(PDO::FETCH_ASSOC); if(count($r)!==1||strtoupper((string)$r[0]['client_code'])!=='DUMMY'||strtolower((string)$r[0]['status'])!=='active')fxfail('exact active DUMMY required'); return $r[0]; }
function fxrole(PDO $p,int $c,string $b): array { $q=$p->prepare("SELECT id,role_label,authority_level FROM client_roles WHERE client_id=? AND UPPER(base_role)=? AND status='active' ORDER BY authority_level DESC,id LIMIT 1");$q->execute([$c,$b]);$r=$q->fetch(PDO::FETCH_ASSOC);if(!is_array($r))fxfail("{$b} role missing");return $r; }
function fxuid(PDO $p,int $c): string { for($i=0;$i<80;$i++){ $u='86'.gmdate('His').str_pad((string)random_int(0,9999),4,'0',STR_PAD_LEFT);$q=$p->prepare('SELECT 1 FROM employees WHERE client_id=? AND user_id=?');$q->execute([$c,$u]);if(!$q->fetchColumn())return $u;}fxfail('user id allocation failed'); }
function fxuuid(): string { $b=random_bytes(16);$b[6]=chr((ord($b[6])&15)|64);$b[8]=chr((ord($b[8])&63)|128);$h=bin2hex($b);return substr($h,0,8).'-'.substr($h,8,4).'-'.substr($h,12,4).'-'.substr($h,16,4).'-'.substr($h,20); }
function fxprepare(PDO $p,string $out): void {
 $c=fxclient($p);$cid=(int)$c['id'];$run=gmdate('YmdHis').'-'.bin2hex(random_bytes(3));$pre=FINFX.' '.$run;$code='FIN'.strtoupper(substr(hash('sha256',$run),0,12));
 $p->prepare("INSERT INTO stores(client_id,store_name,store_code,status,week_start_day,timezone,currency_code) VALUES(?,?,?,'active',1,'Australia/Sydney','AUD')")->execute([$cid,$pre.' Store',$code]);$sid=(int)$p->lastInsertId();
 $h=$p->prepare("INSERT INTO store_weekly_hours(client_id,store_id,day_of_week,start_time,end_time,is_closed,updated_by_employee_id) VALUES(?,?,?,?,?,0,NULL)");foreach(range(1,7) as $d)$h->execute([$cid,$sid,$d,'09:00:00','17:00:00']);
 $e=[];foreach(['DEV','SUPER','ADMIN','USER'] as $b){$r=fxrole($p,$cid,$b);$pw=(string)random_int(10000000,99999999);$u=fxuid($p,$cid);$hash=password_hash($pw,PASSWORD_DEFAULT);$p->prepare("INSERT INTO employees(client_id,store_id,full_name,user_id,login_password,employee_type,pin_code,role_name,client_role_id,hourly_rate,status) VALUES(?,?,?,?,?,?,?,?,?,25.00,'active')")->execute([$cid,$sid,$pre.' '.$b,$u,$hash,$b,$hash,(string)$r['role_label'],(int)$r['id']]);$id=(int)$p->lastInsertId();$p->prepare("INSERT INTO employee_store_access(client_id,employee_id,access_mode,updated_by_employee_id) VALUES(?,?,'selected',?)")->execute([$cid,$id,$id]);$p->prepare('INSERT INTO employee_store_assignments(client_id,employee_id,store_id) VALUES(?,?,?)')->execute([$cid,$id,$sid]);$e[strtolower($b)]=['id'=>$id,'user_id'=>$u,'password'=>$pw,'loa'=>(int)$r['authority_level']];}
 $u=$e['user'];$p->prepare("INSERT INTO attendance_shifts(public_id,client_id,store_id,employee_id,clock_in_at,status,close_reason) VALUES(?,?,?,?,UTC_TIMESTAMP(),'open','none')")->execute([fxuuid(),$cid,$sid,(int)$u['id']]);$shift=(int)$p->lastInsertId();
 $p->prepare("INSERT INTO attendance_disputes(public_id,client_id,shift_id,employee_id,proposed_store_id,dispute_type,reason,origin,status,before_snapshot) VALUES(?,?,?,?,?,'other',?,'employee','pending','{}')")->execute([fxuuid(),$cid,$shift,(int)$u['id'],$sid,'AUTOTEST SEARCH NEEDLE ORCHID '.$run]);
 if(!str_starts_with($out,'/home/dridsheikh/.merdpos-test/'))fxfail('private output required');$dir=dirname($out);if(!is_dir($dir)&&!mkdir($dir,0700,true))fxfail('private dir create failed');
 $fx=['run'=>$run,'prefix'=>$pre,'client'=>['id'=>$cid,'code'=>'DUMMY'],'store'=>['id'=>$sid,'name'=>$pre.' Store'],'employees'=>$e,'business_dates'=>['main'=>'2099-11-11','admin'=>'2099-11-20','dev'=>'2099-11-21','user_denied'=>'2099-11-22']];file_put_contents($out,json_encode($fx,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)."\n",LOCK_EX);chmod($out,0600);echo "FINANCE_E2E_FIXTURE_READY run={$run} client_id={$cid} store={$sid}\n";
}
function fxrows(PDO $p,int $cid,string $run): array { if(!preg_match('/^\d{14}-[a-f0-9]{6}$/',$run))fxfail('invalid run');$pre=FINFX.' '.$run;$q=$p->prepare('SELECT id FROM stores WHERE client_id=? AND store_name LIKE ?');$q->execute([$cid,$pre.'%']);$s=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));$q=$p->prepare('SELECT id FROM employees WHERE client_id=? AND full_name LIKE ?');$q->execute([$cid,$pre.'%']);$e=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));if(count($s)>2||count($e)>6)fxfail('cleanup boundary exceeded');return[$pre,$s,$e]; }
function fxcleanup(PDO $p,string $run): void {
 $c=fxclient($p);$cid=(int)$c['id'];[$pre,$s,$e]=fxrows($p,$cid,$run);if(!$s){echo "FINANCE_E2E_FIXTURE_CLEAN run={$run} stores=0 employees=".count($e)." financial=0\n";return;}$sm=implode(',',array_fill(0,count($s),'?'));$sa=array_merge([$cid],$s);$q=$p->prepare("SELECT public_id FROM financial_submissions WHERE client_id=? AND store_id IN ({$sm})");$q->execute($sa);$pub=$q->fetchAll(PDO::FETCH_COLUMN);
 $p->beginTransaction();try{if($pub){$pm=implode(',',array_fill(0,count($pub),'?'));$p->prepare("DELETE FROM google_sheet_outbox WHERE client_id=? AND aggregate_type='financial_submission' AND aggregate_id IN ({$pm})")->execute(array_merge([$cid],$pub));}$p->prepare("DELETE FROM financial_ledger_entries WHERE client_id=? AND store_id IN ({$sm})")->execute($sa);$p->prepare("UPDATE financial_day_accounts SET closed_by_submission_id=NULL WHERE client_id=? AND store_id IN ({$sm})")->execute($sa);$p->prepare("DELETE FROM financial_day_accounts WHERE client_id=? AND store_id IN ({$sm})")->execute($sa);$p->prepare("DELETE FROM financial_submissions WHERE client_id=? AND store_id IN ({$sm})")->execute($sa);
 if($e){$em=implode(',',array_fill(0,count($e),'?'));$ea=array_merge([$cid],$e);$p->prepare("DELETE FROM attendance_disputes WHERE client_id=? AND employee_id IN ({$em})")->execute($ea);$p->prepare("DELETE FROM attendance_qr_uses WHERE employee_id IN ({$em})")->execute($e);$p->prepare("DELETE FROM attendance_shifts WHERE client_id=? AND employee_id IN ({$em})")->execute($ea);$p->prepare("DELETE FROM employee_store_assignments WHERE client_id=? AND employee_id IN ({$em})")->execute($ea);$p->prepare("DELETE FROM employee_store_access WHERE client_id=? AND employee_id IN ({$em})")->execute($ea);$p->prepare("DELETE FROM employee_hourly_rate_history WHERE client_id=? AND employee_id IN ({$em})")->execute($ea);$p->prepare("DELETE FROM employees WHERE client_id=? AND id IN ({$em}) AND full_name LIKE ?")->execute(array_merge($ea,[$pre.'%']));}
 $p->prepare("DELETE FROM store_weekly_hours WHERE client_id=? AND store_id IN ({$sm})")->execute($sa);$p->prepare("DELETE FROM stores WHERE client_id=? AND id IN ({$sm}) AND store_name LIKE ?")->execute(array_merge($sa,[$pre.'%']));$p->commit();}catch(Throwable $x){if($p->inTransaction())$p->rollBack();throw $x;}echo "FINANCE_E2E_FIXTURE_CLEAN run={$run} stores=".count($s)." employees=".count($e)." financial=".count($pub)."\n";
}
function fxaudit(PDO $p): void { $c=fxclient($p);$cid=(int)$c['id'];$q=$p->prepare('SELECT COUNT(*) FROM stores WHERE client_id=? AND store_name LIKE ?');$q->execute([$cid,FINFX.' %']);$s=(int)$q->fetchColumn();$q=$p->prepare('SELECT COUNT(*) FROM employees WHERE client_id=? AND full_name LIKE ?');$q->execute([$cid,FINFX.' %']);$e=(int)$q->fetchColumn();$q=$p->prepare('SELECT COUNT(*) FROM google_sheet_outbox WHERE client_id=? AND payload LIKE ?');$q->execute([$cid,'%'.FINFX.'%']);$o=(int)$q->fetchColumn();echo "FINANCE_E2E_AUDIT stores={$s} employees={$e} outbox={$o}\n"; }
$a=$argv[1]??'';if($a==='audit'){fxaudit($pdo);exit(0);}if($a==='prepare'){if(empty($argv[2]))fxfail('prepare needs output');fxprepare($pdo,$argv[2]);exit(0);}if($a==='cleanup'){fxcleanup($pdo,$argv[2]??'');exit(0);}fxfail('usage: finance_e2e_fixture.php audit | prepare <private-output> | cleanup <run>');
