<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/web/modules/custom/merdpos_core/src/Integration/PortalGatewayClientInterface.php';
require_once dirname(__DIR__) . '/web/modules/custom/merdpos_core/src/Integration/PortalGatewayClient.php';
use Drupal\merdpos_core\Integration\PortalGatewayClient;
use GuzzleHttp\Client;
use GuzzleHttp\Handler\MockHandler;
use GuzzleHttp\HandlerStack;
use GuzzleHttp\Middleware;
use GuzzleHttp\Psr7\Response;
function store_identity_v1_check(bool $ok,string $message): void { if(!$ok) throw new RuntimeException($message); }
$root=dirname(__DIR__); $repo=dirname($root); $module=$root.'/web/modules/custom/merdpos_core';
$controller=(string)file_get_contents($module.'/src/Controller/AdministrationController.php');
$template=(string)file_get_contents($module.'/templates/merdpos-administration.html.twig');
$js=(string)file_get_contents($module.'/js/administration-v1.js');
$css=(string)file_get_contents($module.'/css/administration-v1.css');
$moduleFile=(string)file_get_contents($module.'/merdpos_core.module');
$deploy=(string)file_get_contents($root.'/tools/namecheap_deploy.sh');
$betaApi=(string)file_get_contents($repo.'/namecheap_beta_live/timesheet_portal/api/store_identity.php');
$betaJs=(string)file_get_contents($repo.'/namecheap_beta_live/timesheet_portal/assets/store-identity.js');
store_identity_v1_check(str_contains($betaApi,"beta_require_permission(" . '$sessionUser' . ", 'stores.profile.manage'"),'Beta Store Identity permission contract missing.');
foreach (['google_maps_url','maps_url_https_google_only','Store Code must be 2–50 characters.','Use an HTTPS Google Maps link.'] as $marker) store_identity_v1_check(str_contains($betaApi,$marker),"Beta Store Identity API marker missing: {$marker}");
foreach (['Internal Store ID','Store Code','Shop address','Google Maps URL','HTTPS Google Maps links only.','Store logo','Open in Google Maps ↗'] as $marker) {
  store_identity_v1_check(str_contains($betaJs,$marker),"Beta Store Identity UI marker missing: {$marker}");
  store_identity_v1_check(str_contains($template,$marker),"Drupal Store Identity UI marker missing: {$marker}");
}
store_identity_v1_check(str_contains($controller,"call('store_identity', 'GET'"),'Drupal signed Store Identity GET missing.');
store_identity_v1_check(str_contains($controller,"call('store_identity', 'POST'"),'Drupal signed Store Identity POST missing.');
store_identity_v1_check(strpos($controller,"call('store_identity', 'POST'") < strpos($controller,"call('admin_directory', 'POST'"),'Store Identity validation must run before the general store write.');
store_identity_v1_check(str_contains($controller,"'google_maps_url'=>trim((string)" . '$request' . "->request->get('google_maps_url', ''))"),'Google Maps URL is not forwarded to Store Identity authority.');
store_identity_v1_check(str_contains($controller, '$body' . "['id'] = " . '$identityStoreId'),'New Store Identity ID is not handed to the remaining governed save flow.');
store_identity_v1_check(str_contains($moduleFile,"'store_identity_available' => false"),'Store Identity theme contract missing.');
store_identity_v1_check(str_contains($template,'name="store_identity_enabled" value="1"'),'Store Identity server-side opt-in marker missing.');
store_identity_v1_check(str_contains($template,'name="logo" accept="image/png,image/jpeg,image/webp"'),'Store Identity logo upload missing.');
store_identity_v1_check(substr_count($template,'merdpos-store-logo-field--identity') >= 2,'DEV Store Identity first-save and edit logo controls are both required.');
store_identity_v1_check(str_contains($js,"[data-store-code]") && str_contains($js,"toUpperCase().replace(/\\s+/g, '-')"),'Store Code normalization missing.');
store_identity_v1_check(str_contains($js,"[data-store-map-link]") && str_contains($js,'stopPropagation()'),'Google Maps row-link interaction guard missing.');
store_identity_v1_check(str_contains($css,'.merdpos-store-map-link') && str_contains($css,'.merdpos-store-summary-logo'),'Store Identity row styling missing.');
foreach (['UPDATE stores','INSERT INTO stores','admin_audit_logs','portal_db(','PDO '] as $forbidden) store_identity_v1_check(!str_contains($controller,$forbidden),"Drupal must not own Store Identity persistence: {$forbidden}");
store_identity_v1_check(str_contains($deploy,'Store Identity parity self-test failed.'),'Store Identity GET-only deploy probe missing.');
$twig=new \Twig\Environment(new \Twig\Loader\ArrayLoader());
$twig->addFunction(new \Twig\TwigFunction('path',static fn(string $route,array $parameters=[],array $options=[]): string=>'/merdpos'));
$twig->parse($twig->tokenize(new \Twig\Source($template,'merdpos-administration.html.twig')));
putenv('MERDPOS_DRUPAL_GATEWAY_URL=https://example.invalid/integrations/portal_gateway.php');
putenv('MERDPOS_DRUPAL_SERVICE_SECRET='.str_repeat('s',32));
putenv('MERDPOS_DRUPAL_CLIENT_ID=1'); putenv('MERDPOS_DRUPAL_ACTOR_USER_ID=1001');
$history=[]; $mock=new MockHandler([new Response(200,['Content-Type'=>'application/json'],'{"success":true,"store_id":9,"stores":[]}')]);
$stack=HandlerStack::create($mock); $stack->push(Middleware::history($history));
$client=new PortalGatewayClient(new Client(['handler'=>$stack]));
$result=$client->call('store_identity','POST',[],['action'=>'save_store','id'=>9,'store_name'=>'Test','store_code'=>'TEST','address'=>'','google_maps_url'=>'https://maps.app.goo.gl/test','status'=>'active'],2);
store_identity_v1_check(($result['status']??'')==='ok','Signed Store Identity mock did not resolve OK.');
store_identity_v1_check(count($history)===1,'Expected one signed Store Identity request.');
$envelope=json_decode((string)$history[0]['request']->getBody(),true,32,JSON_THROW_ON_ERROR);
store_identity_v1_check(($envelope['route']??'')==='store_identity','Signed Store Identity route mismatch.');
store_identity_v1_check(($envelope['method']??'')==='POST','Signed Store Identity method mismatch.');
store_identity_v1_check(($envelope['context_client_id']??0)===2,'Signed Store Identity client context mismatch.');
store_identity_v1_check(($envelope['body']['google_maps_url']??'')==='https://maps.app.goo.gl/test','Google Maps URL missing from signed Store Identity envelope.');
foreach(['MERDPOS_DRUPAL_GATEWAY_URL','MERDPOS_DRUPAL_SERVICE_URL','MERDPOS_DRUPAL_SERVICE_SECRET','MERDPOS_DRUPAL_CLIENT_ID','MERDPOS_DRUPAL_ACTOR_USER_ID'] as $name) putenv($name);
echo "MERDPOS Drupal Store Identity Parity v1 validated.\n";
