<?php
require_once __DIR__ . '/includes/bootstrap.php';
require_once __DIR__ . '/includes/layout.php';
$admin = require_admin();
$clientId = (int)$admin['client_id'];
$page = preg_replace('/[^a-z_]/','', (string)($_GET['page'] ?? 'dashboard'));
$allowed = ['dashboard','employees','stores','categories','products','inventory','suppliers','purchases','sales','reports','devices','audit','settings'];
if (!in_array($page,$allowed,true)) $page='dashboard';

function back(string $page): never { redirect('index.php?page='.$page); }

if ($_SERVER['REQUEST_METHOD']==='POST') {
    verify_csrf();
    $action = post_string('action',40);
    try {
        if ($page==='employees' && $action==='save') {
            $id=post_int('id'); $name=post_string('full_name',190); $user=post_string('user_id',30); $role=strtoupper(post_string('role_name',40)); $rate=post_decimal('hourly_rate'); $status=post_string('status',20); $pin=post_string('pin',20); $store=post_int('store_id');
            if($name===''||!preg_match('/^\d+$/',$user)) throw new RuntimeException('Name and numeric User ID are required.');
            if($id){$sql='UPDATE employees SET full_name=?, user_id=?, role_name=?, employee_type=?, hourly_rate=?, status=?, store_id=?'.($pin!==''?', login_password=?, pin_code=?':'').' WHERE id=? AND client_id=?';$args=[$name,$user,$role,$role,$rate,$status,$store];if($pin!==''){$h=password_hash($pin,PASSWORD_DEFAULT);$args[]=$h;$args[]=$h;}$args[]=$id;$args[]=$clientId;$pdo->prepare($sql)->execute($args);}else{if(!preg_match('/^\d{4,20}$/',$pin))throw new RuntimeException('New employee PIN must be 4–20 digits.');$h=password_hash($pin,PASSWORD_DEFAULT);$pdo->prepare('INSERT INTO employees (client_id,store_id,full_name,user_id,login_password,pin_code,employee_type,role_name,hourly_rate,status) VALUES (?,?,?,?,?,?,?,?,?,?)')->execute([$clientId,$store,$name,$user,$h,$h,$role,$role,$rate,$status]);$id=(int)$pdo->lastInsertId();}
            audit($pdo,$admin,'save','employee',(string)$id,$name); flash('success','Employee saved.'); back('employees');
        }
        if ($page==='stores' && $action==='save') {
            $cols=table_columns($pdo,'stores');$id=post_int('id');$name=post_string('store_name',190);$status=post_string('status',20);if($name==='')throw new RuntimeException('Store name is required.');$nameCol=first_existing($cols,['store_name','name']);$statusCol=first_existing($cols,['status']);if(!$nameCol)throw new RuntimeException('Stores table has no supported name column.');
            if($id){$sql="UPDATE stores SET `$nameCol`=?".($statusCol?", `$statusCol`=?":'')." WHERE id=? AND client_id=?";$args=[$name];if($statusCol)$args[]=$status;$args[]=$id;$args[]=$clientId;$pdo->prepare($sql)->execute($args);}else{$columns=['client_id',$nameCol];$values=[$clientId,$name];if($statusCol){$columns[]=$statusCol;$values[]=$status;}$marks=implode(',',array_fill(0,count($values),'?'));$pdo->prepare('INSERT INTO stores (`'.implode('`,`',$columns).'`) VALUES ('.$marks.')')->execute($values);$id=(int)$pdo->lastInsertId();}
            audit($pdo,$admin,'save','store',(string)$id,$name);flash('success','Store saved.');back('stores');
        }
        if ($page==='categories' && $action==='save') {$id=post_int('id');$name=post_string('name',120);$status=post_string('status',20);if($name==='')throw new RuntimeException('Name required.');if($id)$pdo->prepare('UPDATE retail_categories SET name=?,status=? WHERE id=? AND client_id=?')->execute([$name,$status,$id,$clientId]);else{$pdo->prepare('INSERT INTO retail_categories(client_id,name,status) VALUES(?,?,?)')->execute([$clientId,$name,$status]);$id=(int)$pdo->lastInsertId();}audit($pdo,$admin,'save','category',(string)$id,$name);flash('success','Category saved.');back('categories');}
        if ($page==='products' && $action==='save') {$id=post_int('id');$name=post_string('name',255);$barcode=post_string('barcode',191);$sku=post_string('sku',80);$cat=post_int('category_id')?:null;$cost=post_decimal('cost_price');$price=post_decimal('sell_price');$tax=post_decimal('tax_rate');$status=post_string('status',20);if($name===''||$barcode==='')throw new RuntimeException('Name and barcode required.');if($id)$pdo->prepare('UPDATE retail_products SET category_id=?,sku=?,barcode=?,name=?,cost_price=?,sell_price=?,tax_rate=?,status=? WHERE id=? AND client_id=?')->execute([$cat,$sku,$barcode,$name,$cost,$price,$tax,$status,$id,$clientId]);else{$pdo->prepare('INSERT INTO retail_products(client_id,category_id,sku,barcode,name,cost_price,sell_price,tax_rate,status) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$clientId,$cat,$sku,$barcode,$name,$cost,$price,$tax,$status]);$id=(int)$pdo->lastInsertId();}audit($pdo,$admin,'save','product',(string)$id,$name);flash('success','Product saved.');back('products');}
        if ($page==='inventory' && $action==='save') {$store=post_int('store_id');$product=post_int('product_id');$qty=post_decimal('quantity');$reorder=post_decimal('reorder_level');$sp=post_string('store_price',30);$price=$sp===''?null:(float)$sp;if(!$store||!$product)throw new RuntimeException('Store and product required.');$pdo->prepare('INSERT INTO retail_store_inventory(client_id,store_id,product_id,quantity,reorder_level,store_price) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE quantity=VALUES(quantity),reorder_level=VALUES(reorder_level),store_price=VALUES(store_price)')->execute([$clientId,$store,$product,$qty,$reorder,$price]);audit($pdo,$admin,'adjust','inventory',(string)$product,'store='.$store.', qty='.$qty);flash('success','Inventory updated.');back('inventory');}
        if ($page==='suppliers' && $action==='save') {$id=post_int('id');$name=post_string('name',190);$contact=post_string('contact_name',190);$phone=post_string('phone',60);$email=post_string('email',190);$address=post_string('address',1000);$status=post_string('status',20);if($name==='')throw new RuntimeException('Supplier name required.');if($id)$pdo->prepare('UPDATE retail_suppliers SET name=?,contact_name=?,phone=?,email=?,address=?,status=? WHERE id=? AND client_id=?')->execute([$name,$contact,$phone,$email,$address,$status,$id,$clientId]);else{$pdo->prepare('INSERT INTO retail_suppliers(client_id,name,contact_name,phone,email,address,status) VALUES(?,?,?,?,?,?,?)')->execute([$clientId,$name,$contact,$phone,$email,$address,$status]);$id=(int)$pdo->lastInsertId();}audit($pdo,$admin,'save','supplier',(string)$id,$name);flash('success','Supplier saved.');back('suppliers');}
        if ($page==='purchases' && $action==='create') {$store=post_int('store_id');$supplier=post_int('supplier_id')?:null;$product=post_int('product_id');$qty=post_decimal('quantity');$cost=post_decimal('unit_cost');if(!$store||!$product||$qty<=0)throw new RuntimeException('Store, product and quantity required.');$po='PO-'.date('Ymd-His');$pdo->beginTransaction();$pdo->prepare('INSERT INTO retail_purchase_orders(client_id,store_id,supplier_id,po_number,status,ordered_at,created_by) VALUES(?,?,?,?,?,?,?)')->execute([$clientId,$store,$supplier,$po,'ordered',date('Y-m-d H:i:s'),$admin['id']]);$poId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO retail_purchase_order_lines(purchase_order_id,product_id,quantity_ordered,unit_cost) VALUES(?,?,?,?)')->execute([$poId,$product,$qty,$cost]);$pdo->commit();audit($pdo,$admin,'create','purchase_order',(string)$poId,$po);flash('success','Purchase order created.');back('purchases');}
        if ($page==='purchases' && $action==='receive') {$poId=post_int('id');$pdo->beginTransaction();$q=$pdo->prepare('SELECT * FROM retail_purchase_orders WHERE id=? AND client_id=? FOR UPDATE');$q->execute([$poId,$clientId]);$po=$q->fetch();if(!$po)throw new RuntimeException('PO not found.');$lines=$pdo->prepare('SELECT * FROM retail_purchase_order_lines WHERE purchase_order_id=?');$lines->execute([$poId]);foreach($lines->fetchAll() as $line){$remain=(float)$line['quantity_ordered']-(float)$line['quantity_received'];if($remain>0){$pdo->prepare('UPDATE retail_purchase_order_lines SET quantity_received=quantity_ordered WHERE id=?')->execute([$line['id']]);$pdo->prepare('INSERT INTO retail_store_inventory(client_id,store_id,product_id,quantity) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE quantity=quantity+VALUES(quantity)')->execute([$clientId,$po['store_id'],$line['product_id'],$remain]);}}$pdo->prepare("UPDATE retail_purchase_orders SET status='received',received_at=NOW() WHERE id=?")->execute([$poId]);$pdo->commit();audit($pdo,$admin,'receive','purchase_order',(string)$poId);flash('success','Purchase order received into stock.');back('purchases');}
    } catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof RuntimeException?$e->getMessage():'Operation failed.');back($page);}
}

function rows(PDO $pdo,string $sql,array $args=[]):array{$s=$pdo->prepare($sql);$s->execute($args);return $s->fetchAll();}
$storesCols=table_columns($pdo,'stores');$storeNameCol=first_existing($storesCols,['store_name','name'])??'store_name';
$stores=rows($pdo,"SELECT id, `$storeNameCol` AS store_name FROM stores WHERE client_id=? ORDER BY `$storeNameCol`",[$clientId]);
$categories=rows($pdo,'SELECT * FROM retail_categories WHERE client_id=? ORDER BY name',[$clientId]);
$products=rows($pdo,'SELECT p.*,c.name category_name FROM retail_products p LEFT JOIN retail_categories c ON c.id=p.category_id WHERE p.client_id=? ORDER BY p.name',[$clientId]);
$suppliers=rows($pdo,'SELECT * FROM retail_suppliers WHERE client_id=? ORDER BY name',[$clientId]);

$titles=['dashboard'=>'Dashboard','employees'=>'Employees','stores'=>'Stores','categories'=>'Categories','products'=>'Products','inventory'=>'Inventory','suppliers'=>'Suppliers','purchases'=>'Purchase orders','sales'=>'Sales','reports'=>'Reports','devices'=>'Devices','audit'=>'Audit logs','settings'=>'Settings'];
render_header($titles[$page],$admin);
if($page==='dashboard'){$metrics=['Employees'=>$pdo->prepare('SELECT COUNT(*) FROM employees WHERE client_id=?'),'Stores'=>$pdo->prepare('SELECT COUNT(*) FROM stores WHERE client_id=?'),'Products'=>$pdo->prepare('SELECT COUNT(*) FROM retail_products WHERE client_id=?'),'Today sales'=>$pdo->prepare('SELECT COALESCE(SUM(total),0) FROM retail_sales WHERE client_id=? AND sold_at>=CURDATE()')];echo '<div class="grid">';foreach($metrics as $label=>$stmt){$stmt->execute([$clientId]);echo '<div class="card metric"><strong>'.e((string)$stmt->fetchColumn()).'</strong><span>'.e($label).'</span></div>';}echo '</div>';}
elseif($page==='employees'){$list=rows($pdo,'SELECT id,store_id,full_name,user_id,role_name,employee_type,hourly_rate,status FROM employees WHERE client_id=? ORDER BY full_name',[$clientId]);echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Name<input name="full_name" required></label><label>User ID<input name="user_id" inputmode="numeric" required></label><label>PIN<input name="pin" inputmode="numeric" required></label><label>Role<select name="role_name"><option>USER</option><option>SUPER</option><option>ADMIN</option></select></label><label>Store<select name="store_id">';foreach($stores as $s)echo '<option value="'.$s['id'].'">'.e($s['store_name']).'</option>';echo '</select></label><label>Pay rate<input name="hourly_rate" type="number" step="0.01"></label><input type="hidden" name="status" value="active"><button>Add employee</button></form></div><br><table><tr><th>Name</th><th>User ID</th><th>Role</th><th>Store</th><th>Rate</th><th>Status</th></tr>';foreach($list as $r)echo '<tr><td>'.e($r['full_name']).'</td><td>'.e($r['user_id']).'</td><td>'.e($r['role_name']?:$r['employee_type']).'</td><td>'.e((string)$r['store_id']).'</td><td>'.e((string)$r['hourly_rate']).'</td><td>'.status_badge($r['status']).'</td></tr>';echo '</table>';}
elseif($page==='stores'){echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Store name<input name="store_name" required></label><input type="hidden" name="status" value="active"><button>Add store</button></form></div><br><table><tr><th>ID</th><th>Store</th></tr>';foreach($stores as $r)echo '<tr><td>'.e((string)$r['id']).'</td><td>'.e($r['store_name']).'</td></tr>';echo '</table>';}
elseif($page==='categories'){echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Name<input name="name" required></label><input type="hidden" name="status" value="active"><button>Add category</button></form></div><br><table><tr><th>Name</th><th>Status</th></tr>';foreach($categories as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.status_badge($r['status']).'</td></tr>';echo '</table>';}
elseif($page==='products'){echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Name<input name="name" required></label><label>Barcode<input name="barcode" required></label><label>SKU<input name="sku"></label><label>Category<select name="category_id"><option value="">None</option>';foreach($categories as $c)echo '<option value="'.$c['id'].'">'.e($c['name']).'</option>';echo '</select></label><label>Cost<input name="cost_price" type="number" step="0.01"></label><label>Price<input name="sell_price" type="number" step="0.01"></label><label>Tax %<input name="tax_rate" type="number" step="0.001"></label><input type="hidden" name="status" value="active"><button>Add product</button></form></div><br><table><tr><th>Name</th><th>Barcode</th><th>Category</th><th>Cost</th><th>Price</th><th>Status</th></tr>';foreach($products as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.e($r['barcode']).'</td><td>'.e($r['category_name']).'</td><td>'.e($r['cost_price']).'</td><td>'.e($r['sell_price']).'</td><td>'.status_badge($r['status']).'</td></tr>';echo '</table>';}
elseif($page==='inventory'){$list=rows($pdo,"SELECT i.*,p.name product_name,s.`$storeNameCol` store_name FROM retail_store_inventory i JOIN retail_products p ON p.id=i.product_id JOIN stores s ON s.id=i.store_id WHERE i.client_id=? ORDER BY s.`$storeNameCol`,p.name",[$clientId]);echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Store<select name="store_id">';foreach($stores as $s)echo '<option value="'.$s['id'].'">'.e($s['store_name']).'</option>';echo '</select></label><label>Product<select name="product_id">';foreach($products as $p)echo '<option value="'.$p['id'].'">'.e($p['name']).'</option>';echo '</select></label><label>Quantity<input name="quantity" type="number" step="0.001"></label><label>Reorder<input name="reorder_level" type="number" step="0.001"></label><label>Store price<input name="store_price" type="number" step="0.01"></label><button>Save stock</button></form></div><br><table><tr><th>Store</th><th>Product</th><th>Quantity</th><th>Reorder</th><th>Price</th></tr>';foreach($list as $r)echo '<tr><td>'.e($r['store_name']).'</td><td>'.e($r['product_name']).'</td><td>'.e($r['quantity']).'</td><td>'.e($r['reorder_level']).'</td><td>'.e((string)$r['store_price']).'</td></tr>';echo '</table>';}
elseif($page==='suppliers'){echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="save"><label>Name<input name="name" required></label><label>Contact<input name="contact_name"></label><label>Phone<input name="phone"></label><label>Email<input name="email" type="email"></label><label>Address<input name="address"></label><input type="hidden" name="status" value="active"><button>Add supplier</button></form></div><br><table><tr><th>Name</th><th>Contact</th><th>Phone</th><th>Email</th><th>Status</th></tr>';foreach($suppliers as $r)echo '<tr><td>'.e($r['name']).'</td><td>'.e($r['contact_name']).'</td><td>'.e($r['phone']).'</td><td>'.e($r['email']).'</td><td>'.status_badge($r['status']).'</td></tr>';echo '</table>';}
elseif($page==='purchases'){$list=rows($pdo,"SELECT po.*,s.`$storeNameCol` store_name,sp.name supplier_name FROM retail_purchase_orders po JOIN stores s ON s.id=po.store_id LEFT JOIN retail_suppliers sp ON sp.id=po.supplier_id WHERE po.client_id=? ORDER BY po.id DESC",[$clientId]);echo '<div class="card"><form class="inline" method="post">';csrf_field();echo '<input type="hidden" name="action" value="create"><label>Store<select name="store_id">';foreach($stores as $s)echo '<option value="'.$s['id'].'">'.e($s['store_name']).'</option>';echo '</select></label><label>Supplier<select name="supplier_id"><option value="">None</option>';foreach($suppliers as $s)echo '<option value="'.$s['id'].'">'.e($s['name']).'</option>';echo '</select></label><label>Product<select name="product_id">';foreach($products as $p)echo '<option value="'.$p['id'].'">'.e($p['name']).'</option>';echo '</select></label><label>Quantity<input name="quantity" type="number" step="0.001" required></label><label>Unit cost<input name="unit_cost" type="number" step="0.01"></label><button>Create PO</button></form></div><br><table><tr><th>PO</th><th>Store</th><th>Supplier</th><th>Status</th><th>Action</th></tr>';foreach($list as $r){echo '<tr><td>'.e($r['po_number']).'</td><td>'.e($r['store_name']).'</td><td>'.e($r['supplier_name']).'</td><td>'.status_badge($r['status']).'</td><td>';if($r['status']!=='received'){echo '<form method="post">';csrf_field();echo '<input type="hidden" name="action" value="receive"><input type="hidden" name="id" value="'.$r['id'].'"><button>Receive</button></form>';}echo '</td></tr>';}echo '</table>';}
elseif($page==='sales'){$list=rows($pdo,'SELECT * FROM retail_sales WHERE client_id=? ORDER BY sold_at DESC LIMIT 500',[$clientId]);echo '<table><tr><th>Sale</th><th>Store</th><th>Cashier</th><th>Total</th><th>Payment</th><th>Sold at</th></tr>';foreach($list as $r)echo '<tr><td>'.e($r['sale_number']).'</td><td>'.e((string)$r['store_id']).'</td><td>'.e($r['cashier_name']).'</td><td>'.e($r['total']).'</td><td>'.e($r['payment_method']).'</td><td>'.e($r['sold_at']).'</td></tr>';echo '</table>';}
elseif($page==='reports'){$r=rows($pdo,"SELECT store_id,COUNT(*) transactions,COALESCE(SUM(total),0) sales,COALESCE(SUM(discount),0) discounts FROM retail_sales WHERE client_id=? GROUP BY store_id ORDER BY store_id",[$clientId]);echo '<table><tr><th>Store ID</th><th>Transactions</th><th>Sales</th><th>Discounts</th></tr>';foreach($r as $x)echo '<tr><td>'.e((string)$x['store_id']).'</td><td>'.e((string)$x['transactions']).'</td><td>'.e($x['sales']).'</td><td>'.e($x['discounts']).'</td></tr>';echo '</table>';}
elseif($page==='devices'){$cols=table_columns($pdo,'devices');$list=rows($pdo,'SELECT * FROM devices WHERE client_id=? ORDER BY id DESC',[$clientId]);echo '<table><tr>';foreach(array_slice($cols,0,8) as $c)echo '<th>'.e($c).'</th>';echo '</tr>';foreach($list as $r){echo '<tr>';foreach(array_slice($cols,0,8) as $c)echo '<td>'.e((string)($r[$c]??'')).'</td>';echo '</tr>';}echo '</table>';}
elseif($page==='audit'){$list=rows($pdo,'SELECT * FROM admin_audit_logs WHERE client_id=? ORDER BY id DESC LIMIT 500',[$clientId]);echo '<table><tr><th>When</th><th>Employee</th><th>Action</th><th>Entity</th><th>Details</th></tr>';foreach($list as $r)echo '<tr><td>'.e($r['created_at']).'</td><td>'.e((string)$r['employee_id']).'</td><td>'.e($r['action']).'</td><td>'.e($r['entity_type']).' #'.e($r['entity_id']).'</td><td>'.e($r['details']).'</td></tr>';echo '</table>';}
else{echo '<div class="card"><p><b>Admin version:</b> '.e(ADMIN_VERSION).'</p><p><b>Authenticated employee:</b> '.e($admin['full_name']).'</p><p><b>Client:</b> '.e((string)$clientId).'</p><p class="muted">Configuration remains in backend/api/config.php and is not included in this package.</p></div>';}
render_footer();
